#include "Element.h"
#include "Circuit.h"
#include "Probe.h"

// --- Cereal Polymorphic Registrations ---
// This file exists to explicitly instantiate the serialization code for each
// element type.

CEREAL_REGISTER_TYPE(Resistor)
CEREAL_REGISTER_TYPE(Capacitor)
CEREAL_REGISTER_TYPE(Inductor)
CEREAL_REGISTER_TYPE(IndependentVoltageSource)
CEREAL_REGISTER_TYPE(IndependentCurrentSource)
CEREAL_REGISTER_TYPE(PulseVoltageSource)
CEREAL_REGISTER_TYPE(WaveformVoltageSource)
CEREAL_REGISTER_TYPE(PhaseVoltageSource)
CEREAL_REGISTER_TYPE(SinusoidalVoltageSource)

CEREAL_REGISTER_TYPE(PulseCurrentSource)
CEREAL_REGISTER_TYPE(VoltageControlledVoltageSource)
CEREAL_REGISTER_TYPE(VoltageControlledCurrentSource)
CEREAL_REGISTER_TYPE(CurrentControlledCurrentSource)
CEREAL_REGISTER_TYPE(CurrentControlledVoltageSource)
CEREAL_REGISTER_TYPE(Diode)
CEREAL_REGISTER_TYPE(Ground)
CEREAL_REGISTER_TYPE(CircuitWire)
CEREAL_REGISTER_TYPE(WirelessVoltageSource)

// Probe types
CEREAL_REGISTER_TYPE(VoltageProbe)
CEREAL_REGISTER_TYPE(CurrentProbe)
CEREAL_REGISTER_TYPE(PowerProbe)
CEREAL_REGISTER_TYPE(DifferentialProbe)

CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, Resistor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, Capacitor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, Inductor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, IndependentVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, IndependentCurrentSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, PulseVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, WaveformVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, PhaseVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, SinusoidalVoltageSource)

CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, PulseCurrentSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, VoltageControlledVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, VoltageControlledCurrentSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, CurrentControlledCurrentSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, CurrentControlledVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, Diode)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, Ground)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, CircuitWire)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Element, WirelessVoltageSource)

// Probe polymorphic relations
CEREAL_REGISTER_POLYMORPHIC_RELATION(Probe, VoltageProbe)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Probe, CurrentProbe)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Probe, PowerProbe)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Probe, DifferentialProbe)